#ifndef __HOST_COMMANDS__
#define __HOST_COMMANDS__
#define HOST_FORWARD_FRAME_SIZE 4
#define HOST_BACKWARD_FRAME_SIZE 3
#define SLAVE_COMMAND 0x00
#define MASTER_COMMAND 0xAA
	#define ENUMERATE 0x1
	#define DEVICE_COUNT 0x2
#define RESPONSE_1BYTE 0xAA 
#define RESPONSE_2BYTE 0xbb
	#define ACK 0xFF
	#define NAK 0x00
	#define RESPONSE_OFFSET 0
	#define RESPONSE_1BYTE_OFFSET 1
	#define RESPONSE_2BYTE_OFFSET 2
#define RESPONSE_BYTE(response, res) (response[RESPONSE_OFFSET] = RESPONSE_1BYTE, response[RESPONSE_1BYTE_OFFSET] = res, response[RESPONSE_2BYTE_OFFSET] = 0)
#define RESPONSE_ACK(response) (response[RESPONSE_OFFSET] = RESPONSE_1BYTE, response[RESPONSE_1BYTE_OFFSET] = ACK, response[RESPONSE_2BYTE_OFFSET] = 0)
#define RESPONSE_NAK(response) (response[RESPONSE_OFFSET] = RESPONSE_1BYTE, response[RESPONSE_1BYTE_OFFSET] = NAK, response[RESPONSE_2BYTE_OFFSET] = 0)

#endif
